# Generated by Django 5.1.6 on 2025-02-26 05:51

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "tag_number",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Tag #"
                    ),
                ),
                (
                    "common_name",
                    models.CharField(max_length=100, verbose_name="Common Name"),
                ),
                (
                    "botanical_name",
                    models.CharField(max_length=100, verbose_name="Botanical Name"),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("diameter", models.CharField(blank=True, max_length=20, null=True)),
                ("height", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "crown_height",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "crown_spread",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "health",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("80% - Excellent", "80% - Excellent"),
                            ("60% - Fair", "60% - Fair"),
                            ("40% - Poor", "40% - Poor"),
                            ("20% - Critical", "20% - Critical"),
                            ("0% - Dead", "0% - Dead"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_update", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "alternate_tag",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Tag ##"
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "contributors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contributed_trees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tree",
                "verbose_name_plural": "Trees",
            },
        ),
    ]
